import { db } from '@/lib/db'
import type { Transaction } from '@/types'

/**
 * Data-integrity layer.
 *
 * ⚠️ BROKEN BY DESIGN — DO NOT WIRE `checkIntegrity` / `healPocketBalances`
 * BACK INTO THE UI. The banner + Config panel that used them were removed
 * (2026-07-09) because their premise is false: a pocket's **opening balance**
 * (set at creation in onboarding / addPocket / platform creation) is stored
 * directly on `pocket.balance` and is NEVER written to the ledger. So
 * `computePocketBalance` (= Σ ledger) is always LOWER than the true balance by
 * the opening amount → every real pocket looks "drifted" → healing overwrote
 * correct balances with the too-low ledger sum, destroying the opening amount.
 * To make this usable, first record opening balances as ledger entries (or add
 * an `opening_balance` field) so truth = opening + Σ ledger. Only
 * `isEntityLinkedTransaction` below is live (used by HistoryPage).
 *
 * `pocket.balance` is a running total maintained by hand across many write
 * paths (income, expense, transfer, event confirm, weekly close, history
 * edit/delete). If any path has a bug — or a sync/crash applies a partial
 * write — the stored balance silently drifts from the truth and nothing
 * detects it. These functions recompute a balance from the transaction ledger
 * ONLY (see the warning above — this excludes opening balances).
 *
 * Invariants recomputed here:
 *  - cash / bank pocket: balance = Σ signed(txns on the pocket)
 *  - platform wallet:    balance = Σ signed(txns on the pocket)
 *                                  − Σ amount of its platform_payout events
 *    Rationale: the weekly close moves the closed amount OUT of the wallet
 *    into a payout event (no offsetting transaction is written on the wallet),
 *    so every open or collected close must be subtracted back out.
 */

export interface BalanceDrift {
  pocketId: string
  pocketName: string
  stored: number
  computed: number
  /** stored − computed. Positive = stored is too high; negative = too low. */
  diff: number
}

/**
 * True when a transaction was generated by the app (confirming a debt,
 * collection, saving, cadena, platform payout or recurring event) rather than
 * entered by hand. Such transactions carry a `reference_id` pointing at the
 * source entity, whose counter (paid_amount, collected_amount, …) would fall
 * out of sync if the transaction were freely edited or deleted from History.
 * Manual income/expense and transfer legs have no `reference_id`.
 */
export function isEntityLinkedTransaction(t: Transaction): boolean {
  return t.reference_id != null
}

/** Signed contribution of a single transaction to its own pocket's balance. */
function signedAmount(t: Transaction): number {
  if (t.type === 'income') return t.amount
  if (t.type === 'expense') return -t.amount
  // transfer: direction lives in reference_type
  if (t.reference_type === 'transfer_in') return t.amount
  if (t.reference_type === 'transfer_out') return -t.amount
  return 0
}

/** Recompute the correct balance of one pocket from the ledger. */
export async function computePocketBalance(pocketId: string): Promise<number> {
  const pocket = await db.pockets.get(pocketId)
  if (!pocket) return 0

  const txns = await db.transactions.where('pocket_id').equals(pocketId).toArray()
  let balance = txns.reduce((sum, t) => sum + signedAmount(t), 0)

  if (pocket.type === 'platform' && pocket.platform_id) {
    const platformId = pocket.platform_id
    const payouts = await db.scheduled_events
      .where('user_id').equals(pocket.user_id)
      .filter(e => e.type === 'platform_payout' && e.reference_id === platformId)
      .toArray()
    balance -= payouts.reduce((sum, e) => sum + e.amount, 0)
  }

  return balance
}

/** Return every pocket whose stored balance disagrees with the ledger. */
export async function checkIntegrity(userId: string): Promise<BalanceDrift[]> {
  const pockets = await db.pockets.where('user_id').equals(userId).toArray()
  const drifts: BalanceDrift[] = []

  for (const pocket of pockets) {
    const computed = await computePocketBalance(pocket.id)
    if (computed !== pocket.balance) {
      drifts.push({
        pocketId: pocket.id,
        pocketName: pocket.name,
        stored: pocket.balance,
        computed,
        diff: pocket.balance - computed,
      })
    }
  }

  return drifts
}

/** Rewrite every drifted pocket balance to its computed (ledger-true) value. */
export async function healPocketBalances(userId: string): Promise<BalanceDrift[]> {
  const drifts = await checkIntegrity(userId)
  await db.transaction('rw', db.pockets, async () => {
    for (const d of drifts) {
      await db.pockets.update(d.pocketId, { balance: d.computed })
    }
  })
  return drifts
}
