import { describe, it, expect, beforeEach } from 'vitest'
import { db } from '@/lib/db'
import { computePocketBalance, checkIntegrity, healPocketBalances, isEntityLinkedTransaction } from '@/lib/integrity'
import type { Pocket, Transaction, Platform, ScheduledEvent } from '@/types'

const USER = 'user-integrity-1'

function pocket(over: Partial<Pocket> & Pick<Pocket, 'id'>): Pocket {
  return {
    user_id: USER, name: 'P', type: 'cash', platform_id: null,
    balance: 0, color: '#000', icon: '💵', is_active: true,
    created_at: '', ...over,
  }
}

function tx(over: Partial<Transaction> & Pick<Transaction, 'id' | 'type' | 'amount' | 'pocket_id'>): Transaction {
  return {
    user_id: USER, category_id: null, platform_id: null,
    reference_id: null, reference_type: null, note: null, receipt_url: null,
    date: '2026-07-01', created_at: '', ...over,
  }
}

beforeEach(async () => {
  await Promise.all([
    db.pockets.clear(), db.transactions.clear(),
    db.platforms.clear(), db.scheduled_events.clear(),
  ])
})

describe('computePocketBalance', () => {
  it('sums income minus expense for a cash/bank pocket', async () => {
    await db.pockets.add(pocket({ id: 'p1', balance: 999 })) // stored is wrong on purpose
    await db.transactions.bulkAdd([
      tx({ id: 't1', type: 'income', amount: 100000, pocket_id: 'p1' }),
      tx({ id: 't2', type: 'income', amount: 50000, pocket_id: 'p1' }),
      tx({ id: 't3', type: 'expense', amount: 30000, pocket_id: 'p1' }),
    ])
    expect(await computePocketBalance('p1')).toBe(120000)
  })

  it('counts transfer legs by direction', async () => {
    await db.pockets.add(pocket({ id: 'p1' }))
    await db.transactions.bulkAdd([
      tx({ id: 'ti', type: 'transfer', amount: 40000, pocket_id: 'p1', reference_type: 'transfer_in' }),
      tx({ id: 'to', type: 'transfer', amount: 15000, pocket_id: 'p1', reference_type: 'transfer_out' }),
    ])
    expect(await computePocketBalance('p1')).toBe(25000)
  })

  it('subtracts pending and confirmed payout events for a platform pocket', async () => {
    // Platform wallet earned 200k, closed (event created), then earned 50k more this week.
    await db.platforms.add({
      id: 'pl1', user_id: USER, name: 'Rappi', color: '#f00',
      payout_day: 4, payout_pocket_id: null, is_active: true,
      created_at: '', last_closed_sunday: '2026-06-28',
    } as Platform)
    await db.pockets.add(pocket({ id: 'w1', type: 'platform', platform_id: 'pl1', balance: 50000 }))
    await db.transactions.bulkAdd([
      tx({ id: 'e1', type: 'income', amount: 200000, pocket_id: 'w1' }),
      tx({ id: 'e2', type: 'income', amount: 50000, pocket_id: 'w1' }),
    ])
    const ev: ScheduledEvent = {
      id: 'ev1', user_id: USER, type: 'platform_payout', reference_id: 'pl1',
      reference_type: 'platform', amount: 200000, due_date: '2026-07-02',
      status: 'pending', actual_pocket_id: null, partial_amount: null,
      remaining_after_partial: null, created_at: '',
    }
    await db.scheduled_events.add(ev)
    // 250k earned − 200k locked into the payout event = 50k truly in the wallet now
    expect(await computePocketBalance('w1')).toBe(50000)
  })
})

describe('checkIntegrity', () => {
  it('reports a pocket whose stored balance drifted from the ledger', async () => {
    await db.pockets.add(pocket({ id: 'p1', name: 'Nequi', balance: 500000 }))
    await db.transactions.add(tx({ id: 't1', type: 'income', amount: 120000, pocket_id: 'p1' }))
    const drift = await checkIntegrity(USER)
    expect(drift).toHaveLength(1)
    expect(drift[0]).toMatchObject({ pocketId: 'p1', pocketName: 'Nequi', stored: 500000, computed: 120000, diff: 380000 })
  })

  it('reports nothing when every pocket matches its ledger', async () => {
    await db.pockets.add(pocket({ id: 'p1', balance: 120000 }))
    await db.transactions.add(tx({ id: 't1', type: 'income', amount: 120000, pocket_id: 'p1' }))
    expect(await checkIntegrity(USER)).toHaveLength(0)
  })
})

describe('isEntityLinkedTransaction', () => {
  it('is true for a transaction generated by confirming an event (has reference_id)', () => {
    expect(isEntityLinkedTransaction(
      tx({ id: 'x', type: 'expense', amount: 1, pocket_id: 'p', reference_id: 'debt-1', reference_type: 'debt' })
    )).toBe(true)
  })

  it('is false for a plain manual income/expense', () => {
    expect(isEntityLinkedTransaction(
      tx({ id: 'x', type: 'income', amount: 1, pocket_id: 'p' })
    )).toBe(false)
  })

  it('is false for a transfer leg (no reference_id)', () => {
    expect(isEntityLinkedTransaction(
      tx({ id: 'x', type: 'transfer', amount: 1, pocket_id: 'p', reference_type: 'transfer_out' })
    )).toBe(false)
  })
})

describe('healPocketBalances', () => {
  it('rewrites drifted balances to the computed value and returns what it fixed', async () => {
    await db.pockets.add(pocket({ id: 'p1', balance: 500000 }))
    await db.transactions.add(tx({ id: 't1', type: 'income', amount: 120000, pocket_id: 'p1' }))
    const fixed = await healPocketBalances(USER)
    expect(fixed).toHaveLength(1)
    expect((await db.pockets.get('p1'))?.balance).toBe(120000)
  })
})
